-- 初始化数据库与当前标准平台表结构

-- 创建数据库（如已存在则忽略）
CREATE DATABASE IF NOT EXISTS egg_minimal CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE egg_minimal;

-- 标准平台用户表（基于当前实现）
CREATE TABLE IF NOT EXISTS `plat_users` (
  `USER_GUID` INT NOT NULL AUTO_INCREMENT COMMENT '用户唯一标识',
  `USER_NAME` VARCHAR(50) NOT NULL UNIQUE COMMENT '用户名（登录名）',
  `USER_REAL_NAME` VARCHAR(50) DEFAULT NULL COMMENT '真实姓名',
  `USER_PWD` VARCHAR(500) NOT NULL COMMENT '用户密码（加密存储）',
  `USER_LEV` INT DEFAULT 1 COMMENT '用户级别：1-普通用户，2-管理员',
  `USER_EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '用户邮箱',
  `USER_MOBILE` VARCHAR(50) DEFAULT NULL COMMENT '用户手机号',
  `USER_AVATAR` VARCHAR(500) DEFAULT NULL COMMENT '用户头像（网络链接）',
  `USER_STATUS` INT DEFAULT 1 COMMENT '用户状态：1-正常，0-禁用',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`USER_GUID`),
  INDEX `idx_user_name` (`USER_NAME`),
  INDEX `idx_user_email` (`USER_EMAIL`),
  INDEX `idx_user_status` (`USER_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标准平台用户表';

-- 用户操作日志表
CREATE TABLE IF NOT EXISTS `plat_user_log` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `USER_GUID` INT NOT NULL COMMENT '用户唯一标识',
  `USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '用户名',
  `OPERATE` VARCHAR(500) DEFAULT NULL COMMENT '操作描述',
  `USER_IP` VARCHAR(45) DEFAULT NULL COMMENT '用户IP(支持IPv6)',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`ID`),
  INDEX `idx_user_guid_time` (`USER_GUID`, `CREATE_TIME`),
  INDEX `idx_user_name` (`USER_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户操作日志';

-- 移动应用管理业务主表
CREATE TABLE IF NOT EXISTS `mobile_app` (
  `APP_ID` INT NOT NULL AUTO_INCREMENT COMMENT '应用ID',
  `APP_NAME` VARCHAR(100) NOT NULL COMMENT '应用名称',
  `APP_FULLNAME` VARCHAR(100) DEFAULT NULL COMMENT '应用全称',
  `APP_TYPE` INT DEFAULT NULL COMMENT '应用类型：1-Android，2-iOS，3-WebApp',
  `APP_ICON` VARCHAR(500) DEFAULT NULL COMMENT '应用图标（网络链接）',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`APP_ID`),
  INDEX `idx_app_name` (`APP_NAME`),
  INDEX `idx_app_type` (`APP_TYPE`),
  INDEX `idx_create_time` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动应用管理业务主表';

-- 移动应用扩展信息表
CREATE TABLE IF NOT EXISTS `mobile_app_info` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '扩展信息ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID',
  `DEVELOPER` VARCHAR(50) DEFAULT NULL COMMENT '开发人员',
  `INTERFACE_DEVELOPER` VARCHAR(50) DEFAULT NULL COMMENT '接口开发人员',
  `DESIGNER` VARCHAR(50) DEFAULT NULL COMMENT '设计人员',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_app_id` (`APP_ID`),
  INDEX `idx_create_time` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动应用扩展信息表';

-- 移动应用版本记录表
CREATE TABLE IF NOT EXISTS `mobile_version` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '版本ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID',
  `VERSION_TYPE` INT NOT NULL COMMENT '版本类型：1-正式版，2-测试版，3-开发版',
  `VERSION` VARCHAR(50) NOT NULL COMMENT '版本号',
  `VERSION_CODE` INT NOT NULL COMMENT '版本序号，用于排序，数值越大版本越新',
  `COMMENT` VARCHAR(500) DEFAULT NULL COMMENT '版本说明',
  `DOWNLOAD_SIZE` VARCHAR(50) DEFAULT NULL COMMENT '下载大小',
  `DOWNLOAD_URL` VARCHAR(300) DEFAULT NULL COMMENT '下载地址',
  `DOWNLOAD_SCAN_IMG` VARCHAR(300) DEFAULT NULL COMMENT '二维码图片',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_app_version_unique` (`APP_ID`, `VERSION_TYPE`, `VERSION`, `VERSION_CODE`),
  KEY `idx_app_id` (`APP_ID`),
  KEY `idx_version_type` (`VERSION_TYPE`),
  KEY `idx_version` (`VERSION`),
  KEY `idx_create_time` (`CREATE_TIME`),
  KEY `idx_version_code` (`APP_ID`, `VERSION_TYPE`, `VERSION_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动应用版本记录表';

-- 移动应用操作日志表
CREATE TABLE IF NOT EXISTS `mobile_app_log` (
  `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '日志ID',
  `VERSION_ID` INT DEFAULT NULL COMMENT '版本ID，对应 mobile_version.ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `ACTION` VARCHAR(50) NOT NULL COMMENT '操作类型：create/update/publish/rollback/delete 等',
  `ACTION_DETAIL` VARCHAR(500) DEFAULT NULL COMMENT '操作描述或差异信息',
  `OPERATOR_ID` INT NOT NULL COMMENT '客户端操作者用户ID',
  `OPERATOR_NAME` VARCHAR(50) DEFAULT NULL COMMENT '客户端操作者用户名快照',
  `RESULT_STATUS` VARCHAR(20) DEFAULT 'success' COMMENT '执行结果：success/fail/pending',
  `CLIENT_IP` VARCHAR(45) DEFAULT NULL COMMENT '操作者IP',
  `EXTRA_DATA` JSON DEFAULT NULL COMMENT '扩展字段，如发布参数、审批信息等',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录时间',
  PRIMARY KEY (`ID`),
  KEY `idx_app` (`APP_ID`),
  KEY `idx_version` (`VERSION_ID`),
  KEY `idx_operator_time` (`OPERATOR_ID`, `CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动应用操作日志';

-- 移动应用授权开发者关系表
CREATE TABLE IF NOT EXISTS `mobile_app_user` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `USER_GUID` INT NOT NULL COMMENT '用户ID，对应 plat_users.USER_GUID',
  `PERMISSIONS` INT DEFAULT NULL COMMENT '权限位掩码，预留扩展',
  `REMARK` VARCHAR(200) DEFAULT NULL COMMENT '备注说明',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '添加人',
  `UPDATER` VARCHAR(50) DEFAULT NULL COMMENT '最后修改人',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_app_user` (`APP_ID`, `USER_GUID`),
  INDEX `idx_user_guid` (`USER_GUID`),
  CONSTRAINT `fk_mobile_app_user_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_mobile_app_user_user`
    FOREIGN KEY (`USER_GUID`) REFERENCES `plat_users`(`USER_GUID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='移动应用授权开发者关系表';

