-- RAG 文档管理系统表结构
-- 用于支持 Milvus 向量数据库的 RAG 知识库功能

-- RAG应用文档主表
CREATE TABLE IF NOT EXISTS `rag_document` (
  `DOC_ID` INT NOT NULL AUTO_INCREMENT COMMENT '文档ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `DOC_NAME` VARCHAR(200) NOT NULL COMMENT '文档名称',
  `DOC_TYPE` VARCHAR(20) NOT NULL COMMENT '文档类型：pdf/docx/doc/md/txt等',
  `DOC_SIZE` BIGINT DEFAULT 0 COMMENT '文档大小（字节）',
  `FILE_PATH` VARCHAR(500) DEFAULT NULL COMMENT '文件存储路径（OSS或本地）',
  `FILE_URL` VARCHAR(500) DEFAULT NULL COMMENT '文件访问URL',
  `STATUS` INT DEFAULT 0 COMMENT '处理状态：0-待处理，1-处理中，2-已完成，3-失败',
  `MILVUS_COLLECTION` VARCHAR(100) DEFAULT NULL COMMENT 'Milvus集合名称（每个应用一个集合）',
  `CHUNK_COUNT` INT DEFAULT 0 COMMENT '分块数量',
  `VECTOR_COUNT` INT DEFAULT 0 COMMENT '向量数量',
  `ERROR_MSG` TEXT DEFAULT NULL COMMENT '错误信息（处理失败时）',
  `UPLOADER_ID` INT NOT NULL COMMENT '上传者ID，对应 plat_users.USER_GUID',
  `UPLOADER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '上传者名称',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`DOC_ID`),
  INDEX `idx_app_id` (`APP_ID`),
  INDEX `idx_status` (`STATUS`),
  INDEX `idx_uploader` (`UPLOADER_ID`),
  INDEX `idx_create_time` (`CREATE_TIME`),
  CONSTRAINT `fk_rag_document_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_rag_document_user`
    FOREIGN KEY (`UPLOADER_ID`) REFERENCES `plat_users`(`USER_GUID`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG应用文档主表';

-- RAG应用文档分块表
CREATE TABLE IF NOT EXISTS `rag_document_chunk` (
  `CHUNK_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '分块ID',
  `DOC_ID` INT NOT NULL COMMENT '文档ID，对应 rag_document.DOC_ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `CHUNK_INDEX` INT NOT NULL COMMENT '分块序号（从0开始）',
  `CHUNK_TEXT` TEXT DEFAULT NULL COMMENT '分块文本内容（用于预览）',
  `CHUNK_SIZE` INT DEFAULT 0 COMMENT '分块大小（字符数）',
  `MILVUS_ID` VARCHAR(100) DEFAULT NULL COMMENT 'Milvus中的向量ID（用于删除和更新）',
  `METADATA` JSON DEFAULT NULL COMMENT '元数据JSON（存储页码、章节等信息）',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`CHUNK_ID`),
  UNIQUE KEY `uk_doc_chunk` (`DOC_ID`, `CHUNK_INDEX`),
  INDEX `idx_app_id` (`APP_ID`),
  INDEX `idx_doc_id` (`DOC_ID`),
  INDEX `idx_milvus_id` (`MILVUS_ID`),
  CONSTRAINT `fk_rag_document_chunk_doc`
    FOREIGN KEY (`DOC_ID`) REFERENCES `rag_document`(`DOC_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_rag_document_chunk_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG应用文档分块表';

-- RAG问答记录表
CREATE TABLE IF NOT EXISTS `rag_question` (
  `QUESTION_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '问题ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `USER_ID` INT NOT NULL COMMENT '提问用户ID，对应 plat_users.USER_GUID',
  `USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '提问用户名称',
  `QUESTION` TEXT NOT NULL COMMENT '用户问题',
  `ANSWER` TEXT DEFAULT NULL COMMENT 'AI回答',
  `SOURCE_DOCS` JSON DEFAULT NULL COMMENT '来源文档列表（JSON，记录检索到的文档和分块）',
  `TOKENS_USED` INT DEFAULT 0 COMMENT '使用的Token数量',
  `COST` DECIMAL(10, 6) DEFAULT 0.000000 COMMENT '成本（可选，单位：元）',
  `RESPONSE_TIME` INT DEFAULT 0 COMMENT '响应时间（毫秒）',
  `FEEDBACK` INT DEFAULT NULL COMMENT '用户反馈：1-有用，0-无用，NULL-未反馈',
  `FEEDBACK_TIME` DATETIME DEFAULT NULL COMMENT '反馈时间',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`QUESTION_ID`),
  INDEX `idx_app_id` (`APP_ID`),
  INDEX `idx_user_id` (`USER_ID`),
  INDEX `idx_create_time` (`CREATE_TIME`),
  INDEX `idx_feedback` (`FEEDBACK`),
  CONSTRAINT `fk_rag_question_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_rag_question_user`
    FOREIGN KEY (`USER_ID`) REFERENCES `plat_users`(`USER_GUID`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG问答记录表';

-- RAG配置表（按 APP_ID 维度，包含分段配置）
CREATE TABLE IF NOT EXISTS `rag_config` (
  `CONFIG_ID` INT NOT NULL AUTO_INCREMENT COMMENT '配置ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  -- Milvus Collection 配置（每个应用独立）
  `MILVUS_COLLECTION` VARCHAR(100) DEFAULT NULL COMMENT 'Milvus集合名称（每个应用一个集合）',
  `VECTOR_DIMENSION` INT DEFAULT 1024 COMMENT '向量维度（创建Collection时必需，如：1024）',
  -- 模型配置
  `EMBEDDING_MODEL` VARCHAR(100) DEFAULT 'qwen2.5-vl-embedding' COMMENT 'Embedding模型名称',
  `LLM_MODEL` VARCHAR(100) DEFAULT 'qwen-plus' COMMENT 'LLM模型名称',
  -- LLM Prompt 配置
  `SYSTEM_PROMPT` TEXT DEFAULT NULL COMMENT '系统提示词（用于 RAG 问答），NULL 时使用代码默认值',
  `USER_PROMPT_TEMPLATE` TEXT DEFAULT NULL COMMENT '用户提示词模板（支持 {context} 和 {question} 变量），NULL 时使用代码默认值',
  -- LLM 参数配置
  `LLM_TEMPERATURE` DECIMAL(3, 2) DEFAULT 0.70 COMMENT 'LLM 温度参数（0.0-2.0），控制输出随机性，默认0.7',
  `LLM_MAX_TOKENS` INT DEFAULT 2000 COMMENT 'LLM 最大 Token 数（1-8000），控制输出长度，默认2000',
  `LLM_TOP_P` DECIMAL(3, 2) DEFAULT 0.80 COMMENT 'LLM Top P 参数（0.0-1.0），控制核采样，默认0.8',
  -- 检索配置（用户可调整）
  `TOP_K` INT DEFAULT 5 COMMENT '检索Top K数量',
  `SIMILARITY_THRESHOLD` DECIMAL(5, 4) DEFAULT 0.4000 COMMENT '相似度阈值（0-1）',
  -- 索引配置（影响性能，用户可调整）
  `INDEX_TYPE` VARCHAR(50) DEFAULT 'HNSW' COMMENT '索引类型：HNSW（高质量）/IVF_FLAT（经济）/IVF_PQ（压缩）/AUTOINDEX（自动）',
  `INDEX_PARAMS` JSON DEFAULT NULL COMMENT '索引参数（JSON对象），如：{"M": 16, "efConstruction": 200, "nlist": 1024}。注意：HNSW用M/efConstruction，IVF用nlist，IVF_PQ用nlist/m。NULL时使用默认参数',
  -- Rerank 重排序配置（可选功能）
  `RERANK_ENABLED` TINYINT DEFAULT 0 COMMENT '是否启用Rerank重排序：1-启用，0-禁用',
  `RERANK_MODEL` VARCHAR(100) DEFAULT NULL COMMENT 'Rerank模型名称（如：bge-reranker-base、bge-reranker-large等）',
  `RERANK_TOP_K` INT DEFAULT 10 COMMENT 'Rerank的Top K数量（通常比检索TOP_K大，用于重排序候选）',
  `RERANK_PARAMS` JSON DEFAULT NULL COMMENT 'Rerank参数（JSON对象），如：{"top_n": 5, "return_documents": true}',
  -- 文本分段配置（按 APP_ID 维度）
  `CHUNK_MAX_LENGTH` INT DEFAULT 2048 COMMENT '分块最大长度（字符数），默认2048',
  `CHUNK_OVERLAP` INT DEFAULT 100 COMMENT '分块重叠长度（字符数），默认100',
  `CHUNK_SEPARATORS` JSON DEFAULT NULL COMMENT '分隔符列表（JSON数组），如：["\\n\\n\\n", "\\n\\n", "\\n", "。", "！", "？", ". ", "! ", "? ", " ", ""]。NULL时使用默认分隔符',
  -- 系统字段
  `STATUS` INT DEFAULT 1 COMMENT '配置状态：1-启用，0-禁用',
  `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注说明',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `CREATOR` VARCHAR(50) DEFAULT NULL COMMENT '创建人',
  `UPDATER` VARCHAR(50) DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`CONFIG_ID`),
  UNIQUE KEY `uk_app_id` (`APP_ID`),
  INDEX `idx_status` (`STATUS`),
  CONSTRAINT `fk_rag_config_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG配置表（按APP_ID维度）';

-- RAG 会话表
CREATE TABLE IF NOT EXISTS `rag_session` (
  `SESSION_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '会话ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID',
  `USER_ID` INT NOT NULL COMMENT '用户ID，对应 plat_users.USER_GUID',
  `USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '用户名称',
  `SESSION_TITLE` VARCHAR(200) DEFAULT NULL COMMENT '会话标题（首条问题摘要或用户自定义）',
  `STATUS` TINYINT DEFAULT 0 COMMENT '会话状态：0-正常，1-归档/结束',
  `EXTRA` JSON DEFAULT NULL COMMENT '会话扩展信息（JSON，如当时的模型配置等）',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `UPDATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`SESSION_ID`),
  INDEX `idx_app_id` (`APP_ID`),
  INDEX `idx_user` (`USER_ID`),
  INDEX `idx_status` (`STATUS`),
  INDEX `idx_create_time` (`CREATE_TIME`),
  CONSTRAINT `fk_rag_session_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_rag_session_user`
    FOREIGN KEY (`USER_ID`) REFERENCES `plat_users`(`USER_GUID`)
    ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG 会话表';

-- RAG 会话消息表
CREATE TABLE IF NOT EXISTS `rag_session_message` (
  `MESSAGE_ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '消息ID',
  `SESSION_ID` BIGINT NOT NULL COMMENT '会话ID，对应 rag_session.SESSION_ID',
  `APP_ID` INT NOT NULL COMMENT '应用ID，对应 mobile_app.APP_ID（冗余）',
  `USER_ID` INT DEFAULT NULL COMMENT '用户ID：user消息为用户ID，assistant消息可为NULL或系统ID',
  `ROLE` ENUM('user','assistant') NOT NULL COMMENT '角色：user/assistant',
  `CONTENT` LONGTEXT NOT NULL COMMENT '消息内容（用户问题或助手回答）',
  `SOURCE_DOCS` JSON DEFAULT NULL COMMENT '检索到的文档列表（仅assistant消息使用）',
  `TOKENS_USED` INT DEFAULT 0 COMMENT '本次回复使用的Token数（assistant）',
  `RESPONSE_TIME` INT DEFAULT 0 COMMENT '本次回复耗时（毫秒，assistant）',
  `STREAMED` TINYINT DEFAULT 0 COMMENT '是否通过流式生成：0-否，1-是',
  `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`MESSAGE_ID`),
  INDEX `idx_session` (`SESSION_ID`),
  INDEX `idx_app_id` (`APP_ID`),
  INDEX `idx_user` (`USER_ID`),
  INDEX `idx_role` (`ROLE`),
  INDEX `idx_create_time` (`CREATE_TIME`),
  CONSTRAINT `fk_rag_session_message_session`
    FOREIGN KEY (`SESSION_ID`) REFERENCES `rag_session`(`SESSION_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_rag_session_message_app`
    FOREIGN KEY (`APP_ID`) REFERENCES `mobile_app`(`APP_ID`)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='RAG 会话消息表';
